var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/dogs/new/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__6aa510f8._.js")
R.c("server/chunks/ssr/Documentos_k9-training-platform_f67f2dab._.js")
R.c("server/chunks/ssr/Documentos_k9-training-platform_d18c84cd._.js")
R.c("server/chunks/ssr/72af9_next_dist_compiled_@opentelemetry_api_index_57f910e1.js")
R.c("server/chunks/ssr/[root-of-the-server]__4d2efe17._.js")
R.c("server/chunks/ssr/72af9_next_dist_909ae1c1._.js")
R.c("server/chunks/ssr/72af9_next_dist_ac38d255._.js")
R.c("server/chunks/ssr/Documentos_k9-training-platform_src_app_3e2191af._.js")
R.c("server/chunks/ssr/72af9_next_dist_client_components_builtin_global-error_4e4eb7c1.js")
R.c("server/chunks/ssr/[root-of-the-server]__e5e58a7f._.js")
R.c("server/chunks/ssr/Documentos_k9-training-platform_src_app_1d17d0ef._.js")
R.c("server/chunks/ssr/72af9_next_dist_client_components_eafef291._.js")
R.c("server/chunks/ssr/72af9_next_dist_client_components_builtin_forbidden_d68442bd.js")
R.c("server/chunks/ssr/72af9_next_dist_client_components_builtin_unauthorized_9f73631a.js")
R.c("server/chunks/ssr/6b6b6_k9-training-platform__next-internal_server_app_dogs_new_page_actions_bdab2a0f.js")
R.m(56135)
module.exports=R.m(56135).exports
