var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/_global-error/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__21baaf17._.js")
R.c("server/chunks/ssr/Documentos_k9-training-platform_f67f2dab._.js")
R.c("server/chunks/ssr/72af9_next_dist_6d4c80ce._.js")
R.c("server/chunks/ssr/72af9_next_dist_client_components_builtin_global-error_4e4eb7c1.js")
R.c("server/chunks/ssr/72af9_next_dist_compiled_@opentelemetry_api_index_57f910e1.js")
R.c("server/chunks/ssr/72af9_next_dist_909ae1c1._.js")
R.c("server/chunks/ssr/72af9_next_dist_ac38d255._.js")
R.c("server/chunks/ssr/[root-of-the-server]__4d2efe17._.js")
R.c("server/chunks/ssr/Documentos_k9-training-platform_src_app_3e2191af._.js")
R.c("server/chunks/ssr/0d622__next-internal_server_app__global-error_page_actions_de7e11a7.js")
R.m(59474)
module.exports=R.m(59474).exports
